### ISSUE TITLE
ArrayField: error in value_from_object method

### ISSUE THREAD

**Issue by KGuzikowski** [doableware/djongo#490]
There's a big chance that it may not be an error since I've just started using Djongo.

I have a custom User model defined:

```
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Default user for supplierAPI."""
    username = None

    first_name = models.CharField(help_text="first name", max_length=150)
    last_name = models.CharField(help_text="last name", max_length=150)
    email = models.EmailField(help_text="email address", unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

```

And I wanna define a Company model:
```
from djongo import models
from supplierapi.apps.myAuth.models import User


class Owner(models.Model):
    user_id = models.CharField(blank=False, null=False)

    class Meta:
        abstract = True


class Employee(models.Model):
    user_id = models.CharField(blank=False, null=False)
    role = models.CharField(blank=False, null=False, max_length=20)

    class Meta:
        abstract = True


class Role(models.Model):
    name = models.CharField(blank=False, null=False, max_length=20)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.TextField(unique=True, null=False, blank=False)
    description = models.TextField(null=True)
    owner = models.ArrayField(model_container=Owner)
    staff = models.ArrayField(model_container=Employee)
    roles = models.ArrayField(model_container=Role)

    date_created = models.DateField(blank=False, null=False, auto_now_add=True)

    objects = models.DjongoManager()

    def __str__(self):
        return self.name
```

But when I wanna create a new Company via admin page I get such error:
```
Internal Server Error: /admin/Company/company/2/change/
Traceback (most recent call last):
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1582, in _changeform_view
    form = ModelForm(instance=obj)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/forms/models.py", line 293, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/forms/models.py", line 93, in model_to_dict
    data[f.name] = f.value_from_object(instance)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/djongo/models/fields.py", line 333, in value_from_object
    for _dict in value:
TypeError: 'NoneType' object is not iterable
ERROR 2020-10-29 20:35:34,550 log 44220 140336638715648 Internal Server Error: /admin/Company/company/2/change/
Traceback (most recent call last):
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1582, in _changeform_view
    form = ModelForm(instance=obj)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/forms/models.py", line 293, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/django/forms/models.py", line 93, in model_to_dict
    data[f.name] = f.value_from_object(instance)
  File "/home/guzik/Dokumenty/supplierapi/venv/lib/python3.8/site-packages/djongo/models/fields.py", line 333, in value_from_object
    for _dict in value:
TypeError: 'NoneType' object is not iterable
[29/Oct/2020 20:35:34] "GET /admin/Company/company/2/change/ HTTP/1.1" 500 142173
```
I'm lost, because I've been following Djongo docs.

I use:
django==3.0.5
djongo==1.3.3
sqlparse==0.2.4

**Comment by mohammadbabajafari** [comment]
I have exactly the same problem
