### ISSUE TITLE
Missing match token for AddField of type IntegerField when migrating (sql2mongo)

### ISSUE THREAD

**Issue by Btrd29** [doableware/djongo#532]
#### One line description of the issue
SQLDecodeError occurs when applying a migration that contains an ADD IntegerField

#### Detailed description

I'm working with python 3.9, Django 3.0.5, djongo 1.3.4, sqlparse 0.2.4 and MongoDB 3.6.<br><br>

The error occurs when this kind of migration gets processed :<br>
`
        migrations.AddField(
            model_name='user',
            name='field_name',
            field=models.IntegerField(default=0),
        )
`<br>
which produces the following SQL query :<br>
`ALTER TABLE "core_user" ADD COLUMN "field_name" int DEFAULT %(0)s NOT NULL`<br>

The problem was that in the djongo lib, sql2mongo>query.py, _add function, there was a missing match token for integers.
Therefore, when the previous SQL statement was analysed by the _add function, the "int" part was not correctly processed and a SQLDecodeError was thrown.

#### Solved by
I just added the highlighted bit in the following screenshot (`'int',`) and everything is working smoothly now.
![image](https://user-images.githubusercontent.com/22399880/112288009-37d64a00-8c8d-11eb-8381-e851dd46ae0c.png)

#### Stack Trace
If it can be of any help, here is the stacktrace I got :<br>
```
Running migrations:
  Applying core.0002_auto_20210324_1009...Traceback (most recent call last):
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 783, in __init__
    self._query = self.parse()
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 875, in parse
    raise e
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 856, in parse
    return handler(self, statement)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 888, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 425, in __init__
    super().__init__(*args)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 84, in __init__
    super().__init__(*args)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 435, in parse
    self._add(statement)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\sql2mongo\query.py", line 598, in _add
    raise SQLDecodeError(err_key=tok.value,
djongo.exceptions.SQLDecodeError:

        Keyword: int
        Sub SQL: ALTER TABLE "core_user" ADD COLUMN "field_name" int DEFAULT %(0)s NOT NULL
        FAILED SQL: ('ALTER TABLE "core_user" ADD COLUMN "field_name" int DEFAULT %(0)s NOT NULL',)
        Params: ([0],)
        Version: 1.3.4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\my_user\Documents\project\Server\magenoir\manage.py", line 22, in <module>
    main()
  File "C:\Users\my_user\Documents\project\Server\magenoir\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\core\management\commands\migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\migrations\operations\fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\base\schema.py", line 480, in add_field
    self.execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\my_user\Documents\project\Server\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
```

**Comment by Btrd29** [comment]
should be fixed by this https://github.com/nesdis/djongo/commit/df5ffe44a2e54c5cbf0123d2fc3e698868bbe027
