### ISSUE TITLE
can't convert sql == SELECT COUNT(*) AS "__count" FROM "user_user" WHERE "user_user"."is_superuser"

### ISSUE THREAD

**Issue by Laurel-rao** [doableware/djongo#608]
#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>

access url  /admin/user/user/?is_superuser__exact=1

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'testDB2',
        'ENFORCE_SCHEMA': True,
        'CLIENT': {
            'host': '1.1.1.1',
            'port': 27017,
            'username': 'root',
            'password': 'root',
        }
    }
}

```

#### Traceback
<The complete stack trace of the error.>
[29/Mar/2022 15:06:04] "POST /admin/login/?next=/admin/user/user/%3Fis_superuser__exact%3D1 HTTP/1.1" 302 0
Internal Server Error: /admin/user/user/
Traceback (most recent call last):
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 857, in parse
    return handler(self, statement)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 933, in _select
    return SelectQuery(self.db, self.connection_properties, sm, self._params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 116, in __init__
    super().__init__(*args)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 152, in parse
    self.where = WhereConverter(self, statement)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\converters.py", line 27, in __init__
    self.parse()
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\converters.py", line 122, in parse
    params=self.query.params
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\operators.py", line 475, in __init__
    self._statement2ops()
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\operators.py", line 438, in _statement2ops
    if prev_op.lhs is None:
AttributeError: 'NoneType' object has no attribute 'lhs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\cursor.py", line 56, in execute
    params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 784, in __init__
    self._query = self.parse()
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\sql2mongo\query.py", line 885, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError: 

	Keyword: None
	Sub SQL: None
	FAILED SQL: SELECT COUNT(*) AS "__count" FROM "user_user" WHERE "user_user"."is_superuser"
	Params: ()
	Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\options.py", line 749, in get_changelist_instance
    sortable_by,
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\views\main.py", line 100, in __init__
    self.get_results(request)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\contrib\admin\views\main.py", line 235, in get_results
    result_count = paginator.count
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\core\paginator.py", line 97, in count
    return c()
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\models\query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\models\sql\query.py", line 519, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\models\sql\query.py", line 504, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\mypro\workdir\reeko_oa_project\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
[29/Mar/2022 15:06:05] "GET /admin/user/user/?is_superuser__exact=1 HTTP/1.1" 500 235473

**Comment by keder-code-hash** [comment]
Hey can  you be more specific about the error?

**Comment by KonRatt** [comment]
I had quite a similar problem with a query like this one:
`SELECT * FROM "table" WHERE "table"."bool_field"`

It seems like the problem is that `djongo` can't handle the "boolean condition" and expects `"table"."bool_field" = TRUE`.
I found that `Django` has an option for enabling these "boolean condition"s:
https://github.com/django/django/blob/main/django/db/backends/base/operations.py#L648-L653

If i override this config by adding the following to [djongo/operations.py](https://github.com/doableware/djongo/blob/master/djongo/operations.py#L10), it is compared against `TRUE` in the SQL and `djongo` can handle it!
```
    def conditional_expression_supported_in_where_clause(self, expression):
        return False
```

I hope this is useful for others finding this issue.

I might open a pull request containing this soon.

**Comment by pktiuk** [comment]
In my case, solution provided by @KonRatt fixed this issue. 

Thanks :D

**Comment by yash3004** [comment]
thanks @KonRatt  you have resolved my issue

**Comment by syhanjin** [comment]
thanks @KonRatt you have resolved my issue

**Comment by Chichiboof** [comment]
> I had quite a similar problem with a query like this one: `SELECT * FROM "table" WHERE "table"."bool_field"`
> 
> It seems like the problem is that `djongo` can't handle the "boolean condition" and expects `"table"."bool_field" = TRUE`. I found that `Django` has an option for enabling these "boolean condition"s: https://github.com/django/django/blob/main/django/db/backends/base/operations.py#L648-L653
> 
> If i override this config by adding the following to [djongo/operations.py](https://github.com/doableware/djongo/blob/master/djongo/operations.py#L10), it is compared against `TRUE` in the SQL and `djongo` can handle it!
> 
> ```python
>     def conditional_expression_supported_in_where_clause(self, expression):
>         return False
> ```
> 
> I hope this is useful for others finding this issue.
> 
> I might open a pull request containing this soon.

Thanks very much for the help ^^

**Comment by begoon** [comment]
@KonRatt's hack is great, and it works for me in Django 4.0. However, in 4.1, it does not. Django SQL compiler goes into an infinite recursion somewhere. I had to downgrade from 4.1 to 4.0 to be able to use `allauth` with Djongo.

**Comment by begoon** [comment]
Also, the why how I applied the @KonRatt's patch seamlessly is this -- I added the following piece of code to `settings.py`:

```
from djongo.operations import DatabaseOperations

DatabaseOperations.conditional_expression_supported_in_where_clause = (
    lambda *args, **kwargs: False
)

**Comment by HardlyForeal** [comment]
@begoon, once you implemented @KonRatt's fix, is your infinite loop issue still with the same SQL statement?  I have a PR #647 submitted that fixes an infinite loop caused by a new-ish django sql line.  I thought it was happening in 4.0 as well, but maybe I skipped a version.  For me, it's happening with foreign keys where django used to do "select (1) as a from table.field" whereas now it is doing "select %s as a from table.field" and djongo couldn't handle the parameterized "column".  It pulled it as an identifier with the alias "a", but the identifier only referenced itself, so it went into an infinite loop trying to find the table the column was associated with.

**Comment by Archie818** [comment]
>@KonRatt's hack is great, and it works for me in Django 4.0. However, in 4.1, it does not. Django SQL compiler goes into an infinite recursion somewhere. I had to downgrade from 4.1 to 4.0 to be able to use allauth with Djongo.

Thank you begoo! downgrade Django to 4.0 is work for me!
