### ISSUE TITLE
djongo return none on params

### ISSUE THREAD

**Issue by amofogh** [doableware/djongo#645]
Hi, I'm using multi dbs (postgres and djongo)
when I'm reading UserNotification model the seen field is empty and throws `djongo.exceptions.SQLDecodeError:`
###### model
```
class UserNotification(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50)
    description = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    # user = models.ForeignKey(Member, on_delete=models.CASCADE)
    user_id = models.CharField(max_length=10, editable=False,
                               help_text='id of member (because mongo db dont have foreign key !)')
    seen = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id} | {self.title} | {self.user_id}'

```

but in mongo db the seen field is correct 
```
CaroMongo> db.Core_usernotification.find({ seen: false ,user_id: '2'})
[
  {
    _id: ObjectId("6374db2ae994c082b4e43e03"),
    id: Binary(Buffer.from("ff4aad2332d9405ba817c9403707f37c", "hex"), 3),
    title: '2222',
    description: 'testtttttt2222222',
    created: ISODate("2022-11-16T12:44:26.066Z"),
    user_id: '2',
    seen: false
  },
  {
    _id: ObjectId("6375be5ee9017dc4df919487"),
    id: Binary(Buffer.from("7df45e64f3cd44ceb6db6b17ecd7090a", "hex"), 3),
    title: '2222',
    description: 'testtttttt2222222',
    created: ISODate("2022-11-17T04:53:50.584Z"),
    user_id: '2',
    seen: false
  }
]

```
###### my query
```
UserNotification.objects.filter(user_id='2', seen=False)
```
###### my dbrouter in case you need
```
class MongoDbRouter:
    """
    A router to control all database operations on models in the
    set on mongo db or postgres

    help: just add you model name lowercase to route_model_name and it works for mongo db
    make sure you add id field on your model
            id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    """
    route_model_name = {'loginlog', 'connectionlog', 'usernotification', 'operatornotification', 'rfid_log'}

    def db_for_read(self, model, **hints):
        print(1)
        if model._meta.model_name in self.route_model_name:
            print('reading mongoooo')
            return 'mongo'
        return 'default'

    def db_for_write(self, model, **hints):
        print(2)
        if model._meta.model_name in self.route_model_name:
            print('writing mongoooo ')
            return 'mongo'
        return 'default'

    def allow_relation(self, obj1, obj2, **hints):
        print(3)
        if (
                obj1._meta.model_name in self.route_model_name or
                obj2._meta.model_name in self.route_model_name
        ):
            return True
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        print(4)
        print(model_name)
        if model_name in self.route_model_name:
            print('migrate mongo ')
            return db == 'mongo'
        return 'default'

```
i couldn't find a solution 
##### error 
```
djongo.exceptions.SQLDecodeError: 

	Keyword: FAILED SQL: SELECT "Core_usernotification"."id", "Core_usernotification"."title", "Core_usernotification"."description", "Core_usernotification"."created", "Core_usernotification"."user_id", "Core_usernotification"."seen" FROM "Core_usernotification" WHERE (NOT "Core_usernotification"."seen" AND "Core_usernotification"."user_id" = %(0)s) LIMIT 21
Params: ('2',)
Version: 1.3.6
	Sub SQL: None
	FAILED SQL: None
	Params: None
	Version: None
```

#### Traceback
```
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in to_mongo
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 324, in <listcomp>
    docs = [itm.to_mongo() for itm in self._acc]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 69, in to_mongo
    return self.rhs.to_mongo()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/operators.py", line 319, in to_mongo
    if self.op_type() == AndOp:
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/cursor.py", line 65, in fetchmany
    ret.append(self.result.next())
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/query.py", line 797, in __next__
    result = next(self._result_generator)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/sql2mongo/query.py", line 830, in __iter__
    raise exe from e
djongo.exceptions.SQLDecodeError: 

	Keyword: FAILED SQL: SELECT "Core_usernotification"."id", "Core_usernotification"."title", "Core_usernotification"."description", "Core_usernotification"."created", "Core_usernotification"."user_id", "Core_usernotification"."seen" FROM "Core_usernotification" WHERE (NOT "Core_usernotification"."seen" AND "Core_usernotification"."user_id" = %(0)s) LIMIT 21
Params: ('2',)
Version: 1.3.6
	Sub SQL: None
	FAILED SQL: None
	Params: None
	Version: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/cursor.py", line 70, in fetchmany
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/home/electropeyk/code/CaroSignaling/CaroSignaling/Panel/views.py", line 31, in panel_dashboard
    print(UserNotification.objects.filter(user_id='2',seen=False))
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/query.py", line 256, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1208, in execute_sql
    return list(result)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1646, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1646, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/utils.py", line 96, in inner
    with self:
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/home/electropeyk/code/CaroSignaling/Ubuntuenv/lib/python3.10/site-packages/djongo/cursor.py", line 70, in fetchmany
    raise db_exe from e
django.db.utils.DatabaseError
```

**Comment by amofogh** [comment]
according to link below in booleanfileds have to query with field__in=[False]
`UserNotification.objects.filter(user_id='2', seen__in=[False])`
#### not
`UserNotification.objects.filter(user_id='2', seen=False)`

[https://github.com/doableware/djongo/issues/465](https://github.com/doableware/djongo/issues/465)
