### ISSUE TITLE
is the djongo dev died last year last closed was 2023 condolences if so if not please help

### ISSUE THREAD

**Issue by dayojohn19** [doableware/djongo#702]
Please Help it was working before now it is not

#### One line description of the issue
requirements.txt:
asgiref==3.8.1
attrs==24.2.0
autobahn==24.4.2
Automat==24.8.1
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
constantly==23.10.4
cryptography==43.0.1
daphne==4.1.2
defusedxml==0.8.0rc2
django-cors-headers==4.5.0
django-extensions==3.2.3
django-resized==1.0.3
djangorestframework==3.15.1
djongo==1.3.6
dnspython==2.7.0
exceptiongroup==1.2.2
fuckit==4.8.1
google-api-core==2.21.0
google-api-python-client==2.149.0
google-auth==2.35.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.1
googleapis-common-protos==1.65.0
gunicorn==22.0.0
h11==0.14.0
httplib2==0.22.0
hyperlink==21.0.0
idna==3.10
incremental==24.7.2
numpy==2.2.1
oauthlib==3.2.2
orjson==3.10.10
outcome==1.3.0.post0
packaging==24.0
pillow==11.0.0
proto-plus==1.24.0
protobuf==5.28.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
PyJWT==2.9.0
pymongo==3.11.4
pyOpenSSL==24.2.1
pyparsing==3.2.0
pypng==0.20220715.0
PyQRCode==1.2.1
PySocks==1.7.1
python3-openid==3.2.0
pytz==2024.2
qrcode==8.0
requests==2.32.3
requests-oauthlib==2.0.0
rsa==4.9
selenium==4.25.0
service-identity==24.1.0
setuptools==75.6.0
sniffio==1.3.1
social-auth-core==4.5.4
sortedcontainers==2.4.0
tomli==2.0.2
trio==0.27.0
trio-websocket==0.11.1
Twisted==24.7.0
txaio==23.1.1
typing_extensions==4.12.2
uritemplate==4.1.1
urllib3==1.26.6
webcolors==24.11.1
websocket-client==1.8.0
whitenoise==6.6.0
wsproto==1.2.0
zope.interface==7.1.0

#### Python script

<The complete python script used to produce the issue.>

```python

class PlaceProfile(models.Model):
    # placeVisitor = models.ManyToManyField(
    #     Visitor, blank=True, related_name='placeVisitorLists')
    placeCollections = models.ManyToManyField(
        Collection, blank=True,  related_name='placeCollection')
    placeName = models.CharField(max_length=64)
    placePicture = models.URLField()
    placeisVisited = models.BooleanField(default=False)
    placeLastVisited = models.DateTimeField(auto_now=True)
    placeFirstVisited = models.DateTimeField(auto_now_add=True)
    placeProvince = models.ForeignKey(
        'garden.Province', on_delete=models.CASCADE, null=True, related_name='targetPlace')

    # @property
    # def placeVisitorLists(self):
    #     return [visitor.visitorName for visitor in self.placeVisitor.all()]

    def __str__(self):
        return f"{self.placeName}  -  {self.placeProvince.provinceName}"

    def serialize(self):
        return {
            'placeID': self.id,
            'placeUniqueID': self.placeUniqueID,
            'placeName': self.placeName,
            'placePicture': self.placePicture,
            "placeVisitor": [visitor.serialize() for visitor in self.placeVisitor.all()],
            "placeCollections": [visitor.serialize() for visitor in self.placeCollections.all()],
        }

class Province(models.Model):
    provinceName = models.CharField(max_length=64)
    provincePlaces = models.ManyToManyField(
        'garden.PlaceProfile', blank=True,  related_name='provinceplacelists')
    provinceVisitor = models.ManyToManyField('garden.Visitor', blank=True, related_name='provincevisitorlists')

    def __str__(self):
        return f"{self.provinceName}   -   "

    def serialize(self):
        return {
            "provincePlaces": [mem.serialize() for mem in self.provincePlaces.all()],
            "provinceVisitor": [mem.serialize() for mem in self.provinceVisitor.all()],
        }


```

#### Traceback
Traceback (most recent call last):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/query.py", line 808, in __iter__
    yield from iter(self._query)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/query.py", line 167, in __iter__
    yield self._align_results(doc)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/query.py", line 269, in _align_results
    if selected.table == self.left_table:
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/sql_tokens.py", line 133, in table
    return alias2token[name].table
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/sql_tokens.py", line 133, in table
    return alias2token[name].table
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/sql_tokens.py", line 133, in table
    return alias2token[name].table
  [Previous line repeated 919 more times]
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/sql_tokens.py", line 130, in table
    name = self.given_table
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/sql_tokens.py", line 141, in given_table
    name = self._token.get_real_name()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 361, in get_real_name
    return self._get_first_name(dot_idx)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 386, in _get_first_name
    return token.get_name()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 355, in get_name
    return self.get_alias() or self.get_real_name()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 344, in get_alias
    _, ws = self.token_next_by(t=T.Whitespace)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 244, in token_next_by
    return self._token_matching(funcs, idx, end)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 223, in _token_matching
    if func(token):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/sql.py", line 242, in <lambda>
    funcs = lambda tk: imt(tk, i, m, t)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/utils.py", line 100, in imt
    elif types and any(token.ttype in ttype for ttype in types):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/utils.py", line 100, in <genexpr>
    elif types and any(token.ttype in ttype for ttype in types):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/sqlparse/tokens.py", line 19, in __contains__
    return item is not None and (self is item or item[:len(self)] == self)
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/cursor.py", line 76, in fetchone
    return self.result.next()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/query.py", line 797, in __next__
    result = next(self._result_generator)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/sql2mongo/query.py", line 830, in __iter__
    raise exe from e
djongo.exceptions.SQLDecodeError: 

        Keyword: FAILED SQL: SELECT %(0)s AS "a" FROM "garden_province" WHERE "garden_province"."id" = %(1)s LIMIT 1
Params: (1, 1)
Version: 1.3.6
        Sub SQL: None
        FAILED SQL: None
        Params: None
        Version: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/cursor.py", line 81, in fetchone
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nhoj/Desktop/Carpool and Resort Pooling Revised 10:10:24/garden/views.py", line 193, in registrationPage
    if ppform.is_valid():
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/forms/forms.py", line 439, in full_clean
    self._post_clean()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/forms/models.py", line 492, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/base.py", line 1448, in full_clean
    self.clean_fields(exclude=exclude)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/base.py", line 1500, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 755, in clean
    self.validate(value, model_instance)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/fields/related.py", line 1088, in validate
    if not qs.exists():
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/query.py", line 1226, in exists
    return self.query.has_results(using=self.db)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 592, in has_results
    return compiler.has_results()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1366, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1409, in execute_sql
    val = cursor.fetchone()
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/Users/nhoj/Desktop/webpage/env/lib/python3.9/site-packages/djongo/cursor.py", line 81, in fetchone
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by R-shubham** [comment]
MongoDB released an official Django-MongoDB integration this month that you can try: https://github.com/mongodb/django-mongodb-backend
